[workspace]
members = ["arnold", "braid"]
resolver = "2"

[workspace.dependencies]
arnold = { path = "./arnold" }
braid = { path = "./braid" }

bytes = "1"
camino = { version = "1" }
futures = "0.3"
futures-core = "0.3"
futures-util = "0.3"
http = { version = "1" }
http-body = { version = "1" }
http-body-util = { version = "0.1" }
hyper = { version = "<1" }
pin-project = { version = "1" }
rustls = "^0.21"
static-assertions = { version = "1", package = "static_assertions" }
thiserror = { version = "1" }
tokio = { version = "1" }
tokio-rustls = "0.24.1"
tower = { version = "*" }
tracing = { version = "^0.1" }
