[package]
name = "hyperdriver"
version = "0.1.2"
edition = "2021"
description = "Helpful tools for hyper"
license = "MIT"
repository = "https://github.com/alexrudy/hyperdriver"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7"
bytes = "1"
camino = { version = "1", default-features = false, features = ["serde1"] }
dashmap = "5"
futures-core = "0.3"
futures-util = "0.3"
http = { version = "1" }
http-body = { version = "1" }
http-body-util = { version = "0.1" }
humantime-serde = "1.1.1"
hyper = { version = "1", features = ["full"] }
libc = { version = "0.2" }
ouroboros = "0.18"
pem-rfc7468 = { version = "0.7", features = ["alloc"] }
pin-project = { version = "1" }
rustls = "^0.23"
rustls-native-certs = "0.7.0"
serde = { version = "1" }
socket2 = "0.5"
thiserror = { version = "1" }
tokio = { version = "1", features = ["full"] }
tokio-rustls = "0.26"
tower = { version = "0.4", features = [
    "make",
    "util",
], default-features = false }
tracing = { version = "^0.1" }

[dev-dependencies]
static-assertions = { version = "1", package = "static_assertions" }
tracing-subscriber = "0.2"
tempfile = "3"

[features]
default = []
docs = []
incoming = []

[package.metadata.cargo-machete]
ignored = ["humantime-serde"]
