[package]
name = "hyperdriver"
version = "0.1.2"
edition = "2021"
description = "Helpful tools for hyper"
license = "MIT"
repository = "https://github.com/alexrudy/hyperdriver"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
camino = { version = "1", default-features = false }
axum = { version = "0.7", optional = true }
bytes = "1"
dashmap = { version = "5", optional = true }
futures-core = "0.3"
futures-util = "0.3"
http = { version = "1" }
http-body = { version = "1" }
http-body-util = { version = "0.1" }
humantime-serde = { version = "1.1.1", optional = true }
hyper = { version = "1", features = ["full"] }
libc = { version = "0.2", optional = true }
ouroboros = { version = "0.18", optional = true }
pem-rfc7468 = { version = "0.7", features = ["alloc"], optional = true }
pin-project = { version = "1" }
rustls = { version = "0.23", optional = true }
rustls-native-certs = { version = "0.7.0", optional = true }
serde = { version = "1", optional = true }
socket2 = { version = "0.5", optional = true }
thiserror = { version = "1" }
tokio = { version = "1", features = ["full"] }
tokio-rustls = { version = "0.26", optional = true }
tower = { version = "0.4", features = [
    "make",
    "util",
], default-features = false }
tracing = { version = "^0.1" }

[dev-dependencies]
static-assertions = { version = "1", package = "static_assertions" }
tracing-subscriber = "0.3"
tempfile = "3"

[features]
axum = ["dep:axum"]
default = ["client", "server", "discovery", "stream"]
docs = []
incoming = []
client = ["dep:socket2"]
server = ["dep:ouroboros"]
discovery = [
    "server",
    "client",
    "pidfile",
    "stream",
    "dep:humantime-serde",
    "dep:dashmap",
    "dep:serde",
    "camino/serde1",
]
pidfile = ["dep:libc"]
sni = []
stream = []
tls = [
    "dep:rustls-native-certs",
    "dep:rustls",
    "dep:tokio-rustls",
    "dep:pem-rfc7468",
]

[package.metadata.cargo-machete]
ignored = ["humantime-serde"]


[[test]]
name = "server"
path = "tests/server.rs"
required-features = ["server"]

[[test]]
name = "client"
path = "tests/client.rs"
required-features = ["client"]
