[package]
name = "hyperdriver"
version = "0.2.0"
edition = "2021"
description = "Helpful tools for hyper"
license = "MIT"
repository = "https://github.com/alexrudy/hyperdriver"
rust-version = "1.74"
readme = "README.md"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
camino = { version = "1", default-features = false }
axum = { version = "0.7", optional = true }
bytes = "1"
dashmap = { version = "5", optional = true }
futures-core = "0.3"
futures-util = "0.3"
http = { version = "1" }
http-body = { version = "1" }
http-body-util = { version = "0.1" }
humantime-serde = { version = "1.1.1", optional = true }
hyper = { version = "1", features = ["full"] }
libc = { version = "0.2", optional = true }
ouroboros = { version = "0.18", optional = true }
pin-project = { version = "1" }
rustls = { version = "0.23", optional = true, default-features = false, features = [
    "tls12",
    "ring",
] }
rustls-native-certs = { version = "0.7.0", optional = true }
serde = { version = "1", optional = true }
socket2 = { version = "0.5", optional = true }
thiserror = { version = "1" }
tokio = { version = "1", features = ["full"] }
tokio-rustls = { version = "0.26", optional = true, default-features = false, features = [
    "tls12",
    "ring",
] }
tower = { version = "0.4", features = [
    "make",
    "util",
], default-features = false }
tracing = { version = "^0.1" }

[dev-dependencies]
static-assertions = { version = "1", package = "static_assertions" }
tracing-subscriber = "0.3"
tempfile = "3"
clap = { version = "4.5.7" }
pem-rfc7468 = { version = "0.7", features = ["alloc"] }


[features]
axum = ["dep:axum"]
default = ["client", "server", "discovery", "stream"]
docs = []
incoming = []
client = ["incoming", "dep:socket2"]
server = ["incoming", "dep:ouroboros"]
discovery = [
    "server",
    "client",
    "pidfile",
    "stream",
    "dep:humantime-serde",
    "dep:dashmap",
    "dep:serde",
    "camino/serde1",
]
pidfile = ["dep:libc"]
sni = []
stream = []
tls = ["dep:rustls-native-certs", "dep:rustls", "dep:tokio-rustls"]

[[example]]
name = "google"
path = "examples/client/google.rs"
required-features = ["client", "tls"]

[[example]]
name = "hello"
path = "examples/client/hello.rs"
required-features = ["client", "tls"]

[[example]]
name = "httpbin"
path = "examples/client/httpbin.rs"
required-features = ["client", "tls"]

[[example]]
name = "h2-server"
path = "examples/server/h2.rs"
required-features = ["server", "tls"]

[[test]]
name = "server"
path = "tests/server.rs"
required-features = ["server", "client", "stream"]

[[test]]
name = "client"
path = "tests/client.rs"
required-features = ["server", "client", "stream"]

[package.metadata.cargo-machete]
ignored = ["humantime-serde"]

[package.metadata.cargo-udeps.ignore]
normal = ["rustls-native-certs"]

[package.metadata.docs.rs]
all-features = true
