[package]
name = "patron"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper.workspace = true
hyper-util.workspace = true
braid.workspace = true
